var html="";

html += '<FORM name="magazine">';
html += '<center><TABLE border=0">';
html += '<TBODY>';
html += '<TR>';
html += '<TD>';
html += '<nobr>';


html += '<SELECT onChange="window.open(this.form.issue.options[this.form.issue.selectedIndex].value)" name="issue">'; 
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/162/">162';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/161/">161';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/160/">160';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/159/">159';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/158/">158';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/157/">157';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/156/">156';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/155/">155';
html += '<option>2005';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/154/">154';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/153/">153';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/152/">152';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/151/">151';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/150/">150';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/149/">149';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/148/">148';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/147/">147';
html += '<option>2004';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/146/">146';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/145/">145';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/144/">144';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/143/">143';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/142/">142';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/141/">141';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/140/">140';
html += '<option>2003';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/139/">139';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/138/">138';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/137/">137';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/136/">136';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/135/">135';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/134/">134';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/133/">133';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/132/">132';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/131/">131';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/130/">130';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/129/">129';
html += '<option>2002';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/128/">128';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/127/">127';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/126/">126';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/125/">125';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/124/">124';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/123/">123';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/122/">122';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/121/">121'; 
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/120/">120';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/119/">119';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/118/">118';
html += '<option>2001';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/117/">117';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/116/">116';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/115/">115';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/114/">114';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/113/">113';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/112/">112';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/111/">111';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/110/">110';
html += '<option>2000';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/109/">109';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/108/">108';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/107/">107';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/106/">106';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/105/">105';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/104/">104';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/103/">103';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/102/">102';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/101/">101';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/100/">100';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/099/">099';
html += '<option>1999';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/098/">098';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/097/">097';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/096/">096';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/095/">095';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/094/">094';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/093/">093';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/092/">092';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/091/">091';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/090/">090';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/089/">089';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/088/">088';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/087/">087';
html += '<option>1998';
html += '<option> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/086/">086';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/085/">085';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/084/">084';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/083/">083';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/082/">082';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/081/">081';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/080/">080';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/079/">079';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/078/">078';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/077/">077';
html += '<option>1997';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/076/">076';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/075/">075';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/074/">074';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/073/">073';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/072/">072';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/071/">071';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/070/">070';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/069/">069';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/068/">068';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/067/">067';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/066/">066';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/065/">065';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/064/">064';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/063/">063';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/062/">062';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/061/">061';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/060/">060';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/059/">059';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/058/">058';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/057/">057';
html += '<option>1996';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/056/">056';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/055/">055';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/054/">054';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/053/">053';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/052/">052';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/051/">051';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/050/">050';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/049/">049';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/048/">048';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/047/">047';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/046/">046';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/045/">045';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/044/">044';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/043/">043';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/042/">042';
html += '<option>1995';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/041/">041';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/040/">040';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/039/">039';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/038/">038';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/037/">037';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/036/">036';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/035/">035';
html += '<option>1994';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/034/">034';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/033/">033';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/032/">032';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/031/">031';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/030/">030';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/029/">029';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/028/">028';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/027/">027';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/026/">026';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/025/">025';
html += '<option>1993';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/024/">024';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/023/">023';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/022/">022';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/021/">021';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/020/">020';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/019/">019';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#">1992';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/018/">018';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/017/">017';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/016/">016';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/015/">015';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/014/">014';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/013/">013';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/012/">012';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/011/">011';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/010/">010';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#">1991';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/009/">009';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/008/">008';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/007/">007';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/006/">006';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/005/">005';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/004/">004';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/003/">003';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/002/">002';
html += '<OPTION value="http://godsdirectcontact.us/sm21/gbnews/001/">001';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#">1990';
html += '<OPTION value="http://godsdirectcontact.us/sm21/#"> ';

html += '<OPTION value="http://godsdirectcontact.us/sm21/">all';
html += '<OPTION value="http://godsdirectcontact.us/sm21/cnews/www/001/">big5';
html += '<OPTION value="http://godsdirectcontact.us/sm21/enews/www/124/">en';
html += '<OPTION value="http://godsdirectcontact.us/com/news/">images';

html += '</SELECT>'
html += '<INPUT TYPE =BUTTON value="&#31616;&#20307;"  OnClick="window.open(this.form.issue.options[this.form.issue.selectedIndex].value)" style="font-size: 8pt; color: red">';

html += '</FORM>';
html += '<nobr>';
html += '</TD>';
html += '</TR>';
html += '</TBODY>';
html += '</TABLE></center>';
html += '</CENTER>';
document.write(html);
