var html="";
html += '<base target="_blank">';

html += '<FORM name="magazine">';
html += '<center><TABLE border=0">';
html += '<TBODY>';
html += '<TR>';
html += '<TD>';
html += '<nobr>';
html += '<SELECT name="issue">';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/160/">160';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/159/">159';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/158/">158';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/157/">157';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/156/">156';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/155/">155';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/154/">154';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/153/">153';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/152/">152';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/151/">151';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/150/">150';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/149/">149';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/148/">148';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/146/index.html">146';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/145/index.html">145';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/144/index.html">144';
html += '<OPTION value="http://godsdirectcontact.us/sm21/snews/143/index.html">143';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/142/index.htm">142';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/141/index.htm">141';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/140/index.htm">140';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/139/index.htm">139';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/138/index.htm">138';

html += '<OPTION value="http://godsdirectcontact.us/sm21/eNews/snews136/index.html">136';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/135/index.htm">135';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/134/index.htm">134';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/133/index.htm">133';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/132/index.htm">132';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/131/index.htm">131';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/130/index.htm">130';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/129/index.htm">129';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/128/index.htm">128';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/127/index.htm">127';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/126/index.htm">126';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/125/index.htm">125';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/124/index.htm">124';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/123/index.htm">123';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/122/index.htm">122';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/121/index.htm">121'; 
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/120/index.htm">120';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/119/index.htm">119';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/118/index.htm">118';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/117/index.htm">117';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/116/index.html">116';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/115/index.html">115';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/114/index.html">114';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/113/index.html">113';
html += '<OPTION value="http://godsdirectcontact.us/com/eNews/spanish/111/index.html">111';
html += '<OPTION value="http://godsdirectcontact.us/sm21/eNews/index.html">&lt;110';
html += '<OPTION value="http://godsdirectcontact.us/sm21/enewspilot.htm">en';

html += '</SELECT>'
html += '<INPUT TYPE =BUTTON value="Okay" OnClick="window.open(this.form.issue.options[this.form.issue.selectedIndex].value)">';

html += '</FORM>';

html += '<nobr>';
html += '</TD>';
html += '</TR>';
html += '</TBODY>';
html += '</TABLE></center>';
html += '</CENTER>';
document.write(html);